name: Stock Check Scheduler

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 0 */2 * *"
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub Actions

jobs:
  stock-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the stock checker script
      - name: Run Stock Checker
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} # Store sensitive credentials in GitHub Secrets
        run: |
          python StockChecker.py
